### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by lanaschuhmacher** [richie-south/flowers-v2#2]
What do you think of adding your app to [F-Droid](https://f-droid.org/)?
You can open an issue [here](https://gitlab.com/fdroid/rfp/issues) and will be assisted.

**Comment by KerstinMaur** [comment]
It would be awesome if you could add a [LICENSE](https://help.github.com/en/articles/licensing-a-repository) and include .apks in the [releases](https://github.com/richie-south/flowers-v2/releases). 😎
Thank you so much for your awesome app! 👍
